[MO] - adding basic automatic smoke test for hybrid and examples
gargantophob/synthesis pull request #3
Opened 2021-03-11 08:02 UTC by see-quick

PR, which adding automatic smoke test for hybrid example.

Signed-off-by: morsak <xorsak02@stud.fit.vutbr.cz>

2021-03-11 08:57 UTC, xstupi00 commented
I suggest removing a whole directory, `workspace/examples/tests/` because individual benchmarks are present in the parent directory: `workspace/examples/`. In this way, we add redundancies of benchmarks in the workspace without needing them in multiple places. Please, can you remove the mentioned directory and then edit the relevant methods that work with it?

2021-03-11 09:44 UTC, see-quick commented
Yes, I will do that. Thanks for feedback

2021-03-15 07:13 UTC, xstupi00 requested changes
I have one more note. I noticed that you are using `__init__.py` files within packages, but both created files are empty. I think that we do not need them when they do not contain any implementation. There is an implicit namespace package from version `Python3.3` and higher; you can see this [link](https://stackoverflow.com/questions/37139786/is-init-py-not-required-for-packages-in-python-3-3). Thus, if you do not plan any other use of these files, we can remove them.

2021-03-15 07:13 UTC, xstupi00 commented on dynasty/dynasty_tests/smoke_tests/hybrid_test_suite.py
> +            DynastyUtils.getPathToWorkspaceExamples() + '/tests/tests-optimality/herman/5/',
Considered my comment at PR, here will be sufficient to have `/herman/5/`. Please, check whether the input files in this directory contain the right data.

2021-03-17 23:00 UTC, xstupi00 approved these changes

2021-03-17 23:01 UTC, merged